export const CREATE_NEW_USER="CREATE_NEW_USER";
export const LOGIN_USER="LOGIN_USER";
export const LOGOUT_USER="LOGIN_USER";
export const CREATE_NEW_USER_FAILED="CREATE_NEW_USER_FAILED";
export const LOGIN_USER_FAILED="LOGIN_USER_FAILED";

